'<!DOCTYPE HTML>'+lf+
'<html lang="en-US">'+lf+
'<head>'+lf+
'	<meta charset="UTF-8">'+lf+
'	<title>E-mail</title>'+lf+
'<link href="http://brookframework.org/assets/css/bootstrap.css" rel="stylesheet">'+lf+
'<link href="http://brookframework.org/assets/css/bootstrap-responsive.css" rel="stylesheet">'+lf+
'<link href="http://brookframework.org/assets/css/demos.css" rel="stylesheet">'+lf+
'</head>'+lf+
'<body>'+lf+
'<div class="hero-unit" >'+lf+
'	<form action="/cgi-bin/cgi1" method="post" class="form-inline" >'+lf+
'		<label for="email">Put your e-mail here</label>'+lf+
'		<input type="email" name="email" maxlength="30" id="email" required />'+lf+
'		<input type="submit" class="btn" />'+lf+
'	</form>'+lf+
'</div>'+lf+
'</body>'+lf+
'</html>'
