'<!DOCTYPE HTML>' + LineEnding +
'<html lang="en-US">' + LineEnding +
'<head>' + LineEnding +
'	<meta charset="UTF-8">' + LineEnding +
'	<title>XMailer</title>' + LineEnding +
'</head>' + LineEnding +
'<body>' + LineEnding +
'	<form action="/cgi-bin/cgi1.bf/send" method="post">' + LineEnding +
'		Sender: <input type="text" name="Sender" value="Your Name <test@host.com>"/><br />' + LineEnding +
'		Receiver: <input type="text" name="Receiver" value="dest1@host.com" /><br />' + LineEnding +
'		Subject: <input type="text" name="Subject" value="Your subject." /><br />' + LineEnding +
'		<textarea name="Message" cols="30" rows="10">Your message.</textarea><br />' + LineEnding +
'		<input type="submit" />' + LineEnding +
'	</form>' + LineEnding +
'</body>' + LineEnding +
'</html>'
