(*
  Brook defines.

  Copyright (C) 2012 Silvio Clecio.

  http://brookframework.org

  All contributors:
  Plase see the file CONTRIBUTORS.txt, included in this
  distribution.

  See the file LICENSE.txt, included in this distribution,
  for details about the copyright.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*)

{$mode objfpc}{$H+}
{.$DEFINE BROOK_DEBUG}
{$DEFINE BROOK_INLINE}
{$IFDEF BROOK_DEBUG}
 {$DEFINE CGIDEBUG}
{$ENDIF}
